spring:
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swtxpoi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-wait: -1

  security:
    user:
      name: admin
      password: admin
      roles: USER
server:
  port: 8081
  # 设置静态文件路径，js,css等


  #Mybatis Generator configuration
  #dao类和实体类的位置

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
