package com.scout.pois.dao;

import com.scout.pois.entity.Dp;
import com.scout.pois.entity.DpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    long countByExample(DpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int deleteByExample(DpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int insert(Dp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int insertSelective(Dp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    List<Dp> selectByExample(DpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    Dp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dp record, @Param("example") DpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dp record, @Param("example") DpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dp record);
}