package com.scout.pois.dao;

import com.scout.pois.entity.Poi15year;
import com.scout.pois.entity.Poi15yearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Poi15yearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    long countByExample(Poi15yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int deleteByExample(Poi15yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int insert(Poi15year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int insertSelective(Poi15year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    List<Poi15year> selectByExample(Poi15yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    Poi15year selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Poi15year record, @Param("example") Poi15yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Poi15year record, @Param("example") Poi15yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Poi15year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi15year
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Poi15year record);
}