package com.scout.pois.dao;

import com.scout.pois.entity.Poi16year;
import com.scout.pois.entity.Poi16yearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;


public interface Poi16yearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    long countByExample(Poi16yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int deleteByExample(Poi16yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int insert(Poi16year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int insertSelective(Poi16year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    List<Poi16year> selectByExample(Poi16yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    Poi16year selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Poi16year record, @Param("example") Poi16yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Poi16year record, @Param("example") Poi16yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Poi16year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Poi16year record);
}