package com.scout.pois.dao;

import com.scout.pois.entity.Poi17year;
import com.scout.pois.entity.Poi17yearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Poi17yearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    long countByExample(Poi17yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int deleteByExample(Poi17yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int insert(Poi17year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int insertSelective(Poi17year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    List<Poi17year> selectByExample(Poi17yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    Poi17year selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Poi17year record, @Param("example") Poi17yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Poi17year record, @Param("example") Poi17yearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Poi17year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi17year
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Poi17year record);
}