package com.scout.pois.entity;

import java.io.Serializable;

public class Dp extends Poi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.kind1
     *
     * @mbg.generated
     */
    private String kind1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.kind2
     *
     * @mbg.generated
     */
    private String kind2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.gltag
     *
     * @mbg.generated
     */
    private String gltag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.posx
     *
     * @mbg.generated
     */
    private String posx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.posy
     *
     * @mbg.generated
     */
    private String posy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.openstatus
     *
     * @mbg.generated
     */
    private String openstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp.dpcount
     *
     * @mbg.generated
     */
    private Integer dpcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.id
     *
     * @return the value of dp.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.id
     *
     * @param id the value for dp.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.name
     *
     * @return the value of dp.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.name
     *
     * @param name the value for dp.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.address
     *
     * @return the value of dp.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.address
     *
     * @param address the value for dp.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.city
     *
     * @return the value of dp.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.city
     *
     * @param city the value for dp.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.area
     *
     * @return the value of dp.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.area
     *
     * @param area the value for dp.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.kind1
     *
     * @return the value of dp.kind1
     *
     * @mbg.generated
     */
    public String getKind1() {
        return kind1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.kind1
     *
     * @param kind1 the value for dp.kind1
     *
     * @mbg.generated
     */
    public void setKind1(String kind1) {
        this.kind1 = kind1 == null ? null : kind1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.kind2
     *
     * @return the value of dp.kind2
     *
     * @mbg.generated
     */
    public String getKind2() {
        return kind2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.kind2
     *
     * @param kind2 the value for dp.kind2
     *
     * @mbg.generated
     */
    public void setKind2(String kind2) {
        this.kind2 = kind2 == null ? null : kind2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.gltag
     *
     * @return the value of dp.gltag
     *
     * @mbg.generated
     */
    public String getGltag() {
        return gltag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.gltag
     *
     * @param gltag the value for dp.gltag
     *
     * @mbg.generated
     */
    public void setGltag(String gltag) {
        this.gltag = gltag == null ? null : gltag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.posx
     *
     * @return the value of dp.posx
     *
     * @mbg.generated
     */
    public String getPosx() {
        return posx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.posx
     *
     * @param posx the value for dp.posx
     *
     * @mbg.generated
     */
    public void setPosx(String posx) {
        this.posx = posx == null ? null : posx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.posy
     *
     * @return the value of dp.posy
     *
     * @mbg.generated
     */
    public String getPosy() {
        return posy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.posy
     *
     * @param posy the value for dp.posy
     *
     * @mbg.generated
     */
    public void setPosy(String posy) {
        this.posy = posy == null ? null : posy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.openstatus
     *
     * @return the value of dp.openstatus
     *
     * @mbg.generated
     */
    public String getOpenstatus() {
        return openstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.openstatus
     *
     * @param openstatus the value for dp.openstatus
     *
     * @mbg.generated
     */
    public void setOpenstatus(String openstatus) {
        this.openstatus = openstatus == null ? null : openstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.url
     *
     * @return the value of dp.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.url
     *
     * @param url the value for dp.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.comment
     *
     * @return the value of dp.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.comment
     *
     * @param comment the value for dp.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp.dpcount
     *
     * @return the value of dp.dpcount
     *
     * @mbg.generated
     */
    public Integer getDpcount() {
        return dpcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp.dpcount
     *
     * @param dpcount the value for dp.dpcount
     *
     * @mbg.generated
     */
    public void setDpcount(Integer dpcount) {
        this.dpcount = dpcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", kind1=").append(kind1);
        sb.append(", kind2=").append(kind2);
        sb.append(", gltag=").append(gltag);
        sb.append(", posx=").append(posx);
        sb.append(", posy=").append(posy);
        sb.append(", openstatus=").append(openstatus);
        sb.append(", url=").append(url);
        sb.append(", comment=").append(comment);
        sb.append(", dpcount=").append(dpcount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}