package com.scout.pois.entity;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class DpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public DpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dp
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andKind1IsNull() {
            addCriterion("kind1 is null");
            return (Criteria) this;
        }

        public Criteria andKind1IsNotNull() {
            addCriterion("kind1 is not null");
            return (Criteria) this;
        }

        public Criteria andKind1EqualTo(String value) {
            addCriterion("kind1 =", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1NotEqualTo(String value) {
            addCriterion("kind1 <>", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1GreaterThan(String value) {
            addCriterion("kind1 >", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1GreaterThanOrEqualTo(String value) {
            addCriterion("kind1 >=", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1LessThan(String value) {
            addCriterion("kind1 <", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1LessThanOrEqualTo(String value) {
            addCriterion("kind1 <=", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1Like(String value) {
            addCriterion("kind1 like", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1NotLike(String value) {
            addCriterion("kind1 not like", value, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1In(List<String> values) {
            addCriterion("kind1 in", values, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1NotIn(List<String> values) {
            addCriterion("kind1 not in", values, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1Between(String value1, String value2) {
            addCriterion("kind1 between", value1, value2, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind1NotBetween(String value1, String value2) {
            addCriterion("kind1 not between", value1, value2, "kind1");
            return (Criteria) this;
        }

        public Criteria andKind2IsNull() {
            addCriterion("kind2 is null");
            return (Criteria) this;
        }

        public Criteria andKind2IsNotNull() {
            addCriterion("kind2 is not null");
            return (Criteria) this;
        }

        public Criteria andKind2EqualTo(String value) {
            addCriterion("kind2 =", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2NotEqualTo(String value) {
            addCriterion("kind2 <>", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2GreaterThan(String value) {
            addCriterion("kind2 >", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2GreaterThanOrEqualTo(String value) {
            addCriterion("kind2 >=", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2LessThan(String value) {
            addCriterion("kind2 <", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2LessThanOrEqualTo(String value) {
            addCriterion("kind2 <=", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2Like(String value) {
            addCriterion("kind2 like", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2NotLike(String value) {
            addCriterion("kind2 not like", value, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2In(List<String> values) {
            addCriterion("kind2 in", values, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2NotIn(List<String> values) {
            addCriterion("kind2 not in", values, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2Between(String value1, String value2) {
            addCriterion("kind2 between", value1, value2, "kind2");
            return (Criteria) this;
        }

        public Criteria andKind2NotBetween(String value1, String value2) {
            addCriterion("kind2 not between", value1, value2, "kind2");
            return (Criteria) this;
        }

        public Criteria andGltagIsNull() {
            addCriterion("gltag is null");
            return (Criteria) this;
        }

        public Criteria andGltagIsNotNull() {
            addCriterion("gltag is not null");
            return (Criteria) this;
        }

        public Criteria andGltagEqualTo(String value) {
            addCriterion("gltag =", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagNotEqualTo(String value) {
            addCriterion("gltag <>", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagGreaterThan(String value) {
            addCriterion("gltag >", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagGreaterThanOrEqualTo(String value) {
            addCriterion("gltag >=", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagLessThan(String value) {
            addCriterion("gltag <", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagLessThanOrEqualTo(String value) {
            addCriterion("gltag <=", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagLike(String value) {
            addCriterion("gltag like", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagNotLike(String value) {
            addCriterion("gltag not like", value, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagIn(List<String> values) {
            addCriterion("gltag in", values, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagNotIn(List<String> values) {
            addCriterion("gltag not in", values, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagBetween(String value1, String value2) {
            addCriterion("gltag between", value1, value2, "gltag");
            return (Criteria) this;
        }

        public Criteria andGltagNotBetween(String value1, String value2) {
            addCriterion("gltag not between", value1, value2, "gltag");
            return (Criteria) this;
        }

        public Criteria andPosxIsNull() {
            addCriterion("posx is null");
            return (Criteria) this;
        }

        public Criteria andPosxIsNotNull() {
            addCriterion("posx is not null");
            return (Criteria) this;
        }

        public Criteria andPosxEqualTo(String value) {
            addCriterion("posx =", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotEqualTo(String value) {
            addCriterion("posx <>", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxGreaterThan(String value) {
            addCriterion("posx >", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxGreaterThanOrEqualTo(String value) {
            addCriterion("posx >=", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxLessThan(String value) {
            addCriterion("posx <", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxLessThanOrEqualTo(String value) {
            addCriterion("posx <=", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxLike(String value) {
            addCriterion("posx like", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotLike(String value) {
            addCriterion("posx not like", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxIn(List<String> values) {
            addCriterion("posx in", values, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotIn(List<String> values) {
            addCriterion("posx not in", values, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxBetween(String value1, String value2) {
            addCriterion("posx between", value1, value2, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotBetween(String value1, String value2) {
            addCriterion("posx not between", value1, value2, "posx");
            return (Criteria) this;
        }

        public Criteria andPosyIsNull() {
            addCriterion("posy is null");
            return (Criteria) this;
        }

        public Criteria andPosyIsNotNull() {
            addCriterion("posy is not null");
            return (Criteria) this;
        }

        public Criteria andPosyEqualTo(String value) {
            addCriterion("posy =", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotEqualTo(String value) {
            addCriterion("posy <>", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyGreaterThan(String value) {
            addCriterion("posy >", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyGreaterThanOrEqualTo(String value) {
            addCriterion("posy >=", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyLessThan(String value) {
            addCriterion("posy <", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyLessThanOrEqualTo(String value) {
            addCriterion("posy <=", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyLike(String value) {
            addCriterion("posy like", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotLike(String value) {
            addCriterion("posy not like", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyIn(List<String> values) {
            addCriterion("posy in", values, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotIn(List<String> values) {
            addCriterion("posy not in", values, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyBetween(String value1, String value2) {
            addCriterion("posy between", value1, value2, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotBetween(String value1, String value2) {
            addCriterion("posy not between", value1, value2, "posy");
            return (Criteria) this;
        }

        public Criteria andOpenstatusIsNull() {
            addCriterion("openstatus is null");
            return (Criteria) this;
        }

        public Criteria andOpenstatusIsNotNull() {
            addCriterion("openstatus is not null");
            return (Criteria) this;
        }

        public Criteria andOpenstatusEqualTo(String value) {
            addCriterion("openstatus =", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusNotEqualTo(String value) {
            addCriterion("openstatus <>", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusGreaterThan(String value) {
            addCriterion("openstatus >", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusGreaterThanOrEqualTo(String value) {
            addCriterion("openstatus >=", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusLessThan(String value) {
            addCriterion("openstatus <", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusLessThanOrEqualTo(String value) {
            addCriterion("openstatus <=", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusLike(String value) {
            addCriterion("openstatus like", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusNotLike(String value) {
            addCriterion("openstatus not like", value, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusIn(List<String> values) {
            addCriterion("openstatus in", values, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusNotIn(List<String> values) {
            addCriterion("openstatus not in", values, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusBetween(String value1, String value2) {
            addCriterion("openstatus between", value1, value2, "openstatus");
            return (Criteria) this;
        }

        public Criteria andOpenstatusNotBetween(String value1, String value2) {
            addCriterion("openstatus not between", value1, value2, "openstatus");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andDpcountIsNull() {
            addCriterion("dpcount is null");
            return (Criteria) this;
        }

        public Criteria andDpcountIsNotNull() {
            addCriterion("dpcount is not null");
            return (Criteria) this;
        }

        public Criteria andDpcountEqualTo(Integer value) {
            addCriterion("dpcount =", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountNotEqualTo(Integer value) {
            addCriterion("dpcount <>", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountGreaterThan(Integer value) {
            addCriterion("dpcount >", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("dpcount >=", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountLessThan(Integer value) {
            addCriterion("dpcount <", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountLessThanOrEqualTo(Integer value) {
            addCriterion("dpcount <=", value, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountIn(List<Integer> values) {
            addCriterion("dpcount in", values, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountNotIn(List<Integer> values) {
            addCriterion("dpcount not in", values, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountBetween(Integer value1, Integer value2) {
            addCriterion("dpcount between", value1, value2, "dpcount");
            return (Criteria) this;
        }

        public Criteria andDpcountNotBetween(Integer value1, Integer value2) {
            addCriterion("dpcount not between", value1, value2, "dpcount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dp
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dp
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}