package com.scout.pois.entity;

import javax.annotation.PostConstruct;

/**
 * @author:Scout
 * @data:2021/1/21
 * @description:
 */
public class Poi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.PID
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.POINAME
     *
     * @mbg.generated
     */
    private String poiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.LONGITUDE
     *
     * @mbg.generated
     */
    private Position position;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.CONTACT
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.FULLNAME
     *
     * @mbg.generated
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.CLASSNAME
     *
     * @mbg.generated
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.SUBCLASSNAME
     *
     * @mbg.generated
     */
    private String subclassname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.KINDNAME
     *
     * @mbg.generated
     */
    private String kindname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.CHAINNAME
     *
     * @mbg.generated
     */
    private String chainname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.LINKPID
     *
     * @mbg.generated
     */
    private String linkpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi16year.YEAR
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.PID
     *
     * @return the value of poi16year.PID
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.PID
     *
     * @param pid the value for poi16year.PID
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.POINAME
     *
     * @return the value of poi16year.POINAME
     *
     * @mbg.generated
     */
    public String getPoiname() {
        return poiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.POINAME
     *
     * @param poiname the value for poi16year.POINAME
     *
     * @mbg.generated
     */
    public void setPoiname(String poiname) {
        this.poiname = poiname == null ? null : poiname.trim();
    }

    public Position getPosition() {
        return position;
    }

    private double longitude;
    private double latitude;

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public Poi(){

    }

    @PostConstruct
    public void setPosition() {
        this.position = new Position(getLongitude(),getLatitude());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.CONTACT
     *
     * @return the value of poi16year.CONTACT
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.CONTACT
     *
     * @param contact the value for poi16year.CONTACT
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.FULLNAME
     *
     * @return the value of poi16year.FULLNAME
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.FULLNAME
     *
     * @param fullname the value for poi16year.FULLNAME
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.CLASSNAME
     *
     * @return the value of poi16year.CLASSNAME
     *
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.CLASSNAME
     *
     * @param classname the value for poi16year.CLASSNAME
     *
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.SUBCLASSNAME
     *
     * @return the value of poi16year.SUBCLASSNAME
     *
     * @mbg.generated
     */
    public String getSubclassname() {
        return subclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.SUBCLASSNAME
     *
     * @param subclassname the value for poi16year.SUBCLASSNAME
     *
     * @mbg.generated
     */
    public void setSubclassname(String subclassname) {
        this.subclassname = subclassname == null ? null : subclassname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.KINDNAME
     *
     * @return the value of poi16year.KINDNAME
     *
     * @mbg.generated
     */
    public String getKindname() {
        return kindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.KINDNAME
     *
     * @param kindname the value for poi16year.KINDNAME
     *
     * @mbg.generated
     */
    public void setKindname(String kindname) {
        this.kindname = kindname == null ? null : kindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.STATE
     *
     * @return the value of poi16year.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.STATE
     *
     * @param state the value for poi16year.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.CHAINNAME
     *
     * @return the value of poi16year.CHAINNAME
     *
     * @mbg.generated
     */
    public String getChainname() {
        return chainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.CHAINNAME
     *
     * @param chainname the value for poi16year.CHAINNAME
     *
     * @mbg.generated
     */
    public void setChainname(String chainname) {
        this.chainname = chainname == null ? null : chainname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.LINKPID
     *
     * @return the value of poi16year.LINKPID
     *
     * @mbg.generated
     */
    public String getLinkpid() {
        return linkpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.LINKPID
     *
     * @param linkpid the value for poi16year.LINKPID
     *
     * @mbg.generated
     */
    public void setLinkpid(String linkpid) {
        this.linkpid = linkpid == null ? null : linkpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi16year.YEAR
     *
     * @return the value of poi16year.YEAR
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi16year.YEAR
     *
     * @param year the value for poi16year.YEAR
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi16year
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", poiname=").append(poiname);
        sb.append(", contact=").append(contact);
        sb.append(", fullname=").append(fullname);
        sb.append(", classname=").append(classname);
        sb.append(", subclassname=").append(subclassname);
        sb.append(", kindname=").append(kindname);
        sb.append(", state=").append(state);
        sb.append(", chainname=").append(chainname);
        sb.append(", linkpid=").append(linkpid);
        sb.append(", year=").append(year);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
