package com.scout.pois.entity;

import java.io.Serializable;

public class Poi14year extends Poi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi14year
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi14year
     *
     * @mbg.generated
     */

}